FROM golang:1.11-alpine

RUN mkdir -p /go/src/github.com/g10guang/graduation/consumer/post_event
COPY ./post_event /go/src/github.com/g10guang/graduation/consumer/post_event

EXPOSE 10002

WORKDIR /go/src/github.com/g10guang/graduation/consumer/post_event

ENV PATH="${PATH}:/go/src/github.com/g10guang/graduation/consumer/post_event"

CMD post_event