FROM golang:1.11-alpine

RUN mkdir -p /go/src/github.com/g10guang/graduation/consumer/delete_event
COPY ./delete_event /go/src/github.com/g10guang/graduation/consumer/delete_event

EXPOSE 10002

WORKDIR /go/src/github.com/g10guang/graduation/consumer/delete_event

ENV PATH="${PATH}:/go/src/github.com/g10guang/graduation/consumer/delete_event"

CMD delete_event