FROM golang:1.11-alpine

RUN mkdir -p /go/src/github.com/g10guang/graduation/write_api
COPY write_api /go/src/github.com/g10guang/graduation/write_api

EXPOSE 10003

WORKDIR /go/src/github.com/g10guang/graduation/write_api

ENV PATH="${PATH}:/go/src/github.com/g10guang/graduation/write_api"

CMD write_api
